import { ITableAirDeco } from '../types/interfaces';

const usNavyAirDecompressionTable: ITableAirDeco = {
  tableCode: 'USN-AIR-DECO',
  tableName: 'US Navy no decompression table revision 7 - Residual Nitrogen Time for No-Decompression Air Dives',
  tableData: [
    {
      minfsw: 0,
      maxfsw: 30,
      rows: [
        {
          minTime: 372,
          maxTime: 380,
          airTAT: '6:0',
          o2TAT: '2:0',
          ttfs: '0:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 5 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 381,
          maxTime: 420,
          airTAT: '23:0',
          o2TAT: '6:0',
          ttfs: '0:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 22 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          airTAT: '43:0',
          o2TAT: '10:0',
          ttfs: '0:20',
          o2cp: 0.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 42 },
          ],
          o2decoStops: [
            { depth: 20, time: 9 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          airTAT: '72:0',
          o2TAT: '15:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 71 },
          ],
          o2decoStops: [
            { depth: 20, time: 14 },
          ],
        },
        {
          minTime: 541,
          maxTime: 600,
          airTAT: '93:0',
          o2TAT: '20:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 92 },
          ],
          o2decoStops: [
            { depth: 20, time: 19 },
          ],
        },
        {
          minTime: 601,
          maxTime: 660,
          airTAT: '121:0',
          o2TAT: '23:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 120 },
          ],
          o2decoStops: [
            { depth: 20, time: 22 },
          ],
        },
        {
          minTime: 661,
          maxTime: 720,
          airTAT: '159:0',
          o2TAT: '28:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 158 },
          ],
          o2decoStops: [
            { depth: 20, time: 27 },
          ],
        },
      ]
    },
    {
      minfsw: 31,
      maxfsw: 35,
      rows: [
        {
          minTime: 233,
          maxTime: 240,
          ttfs: '0:30',
          airTAT: '5:10',
          o2TAT: '3:10',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 4 },
          ],
          o2decoStops: [
            { depth: 20, time: 2 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '0:30',
          airTAT: '54:10',
          o2TAT: '14:10',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 53 },
          ],
          o2decoStops: [
            { depth: 20, time: 13 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '0:30',
          airTAT: '72:10',
          o2TAT: '19:10',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 71 },
          ],
          o2decoStops: [
            { depth: 20, time: 18 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '0:30',
          airTAT: '89:10',
          o2TAT: '23:10',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 88 },
          ],
          o2decoStops: [
            { depth: 20, time: 22 },
          ],
        },
        {
          minTime: 361,
          maxTime: 420,
          ttfs: '0:30',
          airTAT: '135:10',
          o2TAT: '30:10',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 134 },
          ],
          o2decoStops: [
            { depth: 20, time: 29 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          ttfs: '0:30',
          airTAT: '174:10',
          o2TAT: '44:10',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 173 },
          ],
          o2decoStops: [
            { depth: 20, time: 38 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          ttfs: '0:30',
          airTAT: '229:10',
          o2TAT: '51:10',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 228 },
          ],
          o2decoStops: [
            { depth: 20, time: 45 },
          ],
        },
        {
          minTime: 541,
          maxTime: 600,
          ttfs: '0:30',
          airTAT: '278:10',
          o2TAT: '59:10',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 277 },
          ],
          o2decoStops: [
            { depth: 20, time: 53 },
          ],
        },
        {
          minTime: 601,
          maxTime: 660,
          ttfs: '0:30',
          airTAT: '315:10',
          o2TAT: '69:10',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 314 },
          ],
          o2decoStops: [
            { depth: 20, time: 63 },
          ],
        },
        {
          minTime: 661,
          maxTime: 720,
          ttfs: '0:30',
          airTAT: '343:10',
          o2TAT: '82:10',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 342 },
          ],
          o2decoStops: [
            { depth: 20, time: 71 },
          ],
        },
      ]
    },
    {
      minfsw: 36,
      maxfsw: 40,
      rows: [
        {
          minTime: 164,
          maxTime: 170,
          ttfs: '0:40',
          airTAT: '7:20',
          o2TAT: '3:20',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 6 },
          ],
          o2decoStops: [
            { depth: 20, time: 2 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '0:40',
          airTAT: '15:20',
          o2TAT: '6:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 14 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '0:40',
          airTAT: '22:20',
          o2TAT: '8:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 21 },
          ],
          o2decoStops: [
            { depth: 20, time: 7 },
          ],
        },
        {
          minTime: 191,
          maxTime: 200,
          ttfs: '0:40',
          airTAT: '28:20',
          o2TAT: '10:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 27 },
          ],
          o2decoStops: [
            { depth: 20, time: 9 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '0:40',
          airTAT: '40:20',
          o2TAT: '12:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 39 },
          ],
          o2decoStops: [
            { depth: 20, time: 11 },
          ],
        },
        {
          minTime: 211,
          maxTime: 220,
          ttfs: '0:40',
          airTAT: '53:20',
          o2TAT: '13:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 52 },
          ],
          o2decoStops: [
            { depth: 20, time: 12 },
          ],
        },
        {
          minTime: 221,
          maxTime: 230,
          ttfs: '0:40',
          airTAT: '65:20',
          o2TAT: '17:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 64 },
          ],
          o2decoStops: [
            { depth: 20, time: 16 },
          ],
        },
        {
          minTime: 231,
          maxTime: 240,
          ttfs: '0:40',
          airTAT: '76:20',
          o2TAT: '20:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 75 },
          ],
          o2decoStops: [
            { depth: 20, time: 19 },
          ],
        },
        {
          minTime: 241,
          maxTime: 270,
          ttfs: '0:40',
          airTAT: '102:20',
          o2TAT: '27:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 101 },
          ],
          o2decoStops: [
            { depth: 20, time: 26 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '0:40',
          airTAT: '129:20',
          o2TAT: '34:20',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 128 },
          ],
          o2decoStops: [
            { depth: 20, time: 33 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '0:40',
          airTAT: '161:20',
          o2TAT: '44:20',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 160 },
          ],
          o2decoStops: [
            { depth: 20, time: 38 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '0:40',
          airTAT: '185:20',
          o2TAT: '50:20',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 184 },
          ],
          o2decoStops: [
            { depth: 20, time: 44 },
          ],
        },
        {
          minTime: 361,
          maxTime: 420,
          ttfs: '0:40',
          airTAT: '249:20',
          o2TAT: '62:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 248 },
          ],
          o2decoStops: [
            { depth: 20, time: 56 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          ttfs: '0:40',
          airTAT: '322:20',
          o2TAT: '79:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 321 },
          ],
          o2decoStops: [
            { depth: 20, time: 68 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          ttfs: '0:40',
          airTAT: '373:20',
          o2TAT: '91:20',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 372 },
          ],
          o2decoStops: [
            { depth: 20, time: 80 },
          ],
        },
        {
          minTime: 541,
          maxTime: 600,
          ttfs: '0:40',
          airTAT: '411:20',
          o2TAT: '104:20',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 410 },
          ],
          o2decoStops: [
            { depth: 20, time: 93 },
          ],
        },
        {
          minTime: 601,
          maxTime: 660,
          ttfs: '0:40',
          airTAT: '440:20',
          o2TAT: '119:20',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 439 },
          ],
          o2decoStops: [
            { depth: 20, time: 103 },
          ],
        },
        {
          minTime: 661,
          maxTime: 720,
          ttfs: '0:40',
          airTAT: '462:20',
          o2TAT: '128:20',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 461 },
          ],
          o2decoStops: [
            { depth: 20, time: 112 },
          ],
        },
      ]
    },
    {
      minfsw: 41,
      maxfsw: 45,
      rows: [
        {
          minTime: 126,
          maxTime: 130,
          ttfs: '0:50',
          airTAT: '3:30',
          o2TAT: '2:30',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 2 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 131,
          maxTime: 140,
          ttfs: '0:50',
          airTAT: '15:30',
          o2TAT: '6:20',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 14 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 141,
          maxTime: 150,
          ttfs: '0:50',
          airTAT: '26:30',
          o2TAT: '9:30',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 25 },
          ],
          o2decoStops: [
            { depth: 20, time: 8 },
          ],
        },
        {
          minTime: 151,
          maxTime: 160,
          ttfs: '0:50',
          airTAT: '35:30',
          o2TAT: '12:30',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 34 },
          ],
          o2decoStops: [
            { depth: 20, time: 11 },
          ],
        },
        {
          minTime: 161,
          maxTime: 170,
          ttfs: '0:50',
          airTAT: '42:30',
          o2TAT: '15:30',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 41 },
          ],
          o2decoStops: [
            { depth: 20, time: 14 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '0:50',
          airTAT: '60:30',
          o2TAT: '18:30',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 59 },
          ],
          o2decoStops: [
            { depth: 20, time: 17 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '0:50',
          airTAT: '76:30',
          o2TAT: '20:30',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 75 },
          ],
          o2decoStops: [
            { depth: 20, time: 19 },
          ],
        },
        {
          minTime: 191 ,
          maxTime: 200,
          ttfs: '0:50',
          airTAT: '90:30',
          o2TAT: '24:30',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 89 },
          ],
          o2decoStops: [
            { depth: 20, time: 23 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '0:50',
          airTAT: '102:30',
          o2TAT: '28:30',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 101 },
          ],
          o2decoStops: [
            { depth: 20, time: 27 },
          ],
        },
        {
          minTime: 211,
          maxTime: 220,
          ttfs: '0:50',
          airTAT: '113:30',
          o2TAT: '31:30',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 112 },
          ],
          o2decoStops: [
            { depth: 20, time: 30 },
          ],
        },
        {
          minTime: 221,
          maxTime: 230,
          ttfs: '0:50',
          airTAT: '122:30',
          o2TAT: '34:30',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 121 },
          ],
          o2decoStops: [
            { depth: 20, time: 33 },
          ],
        },
        {
          minTime: 231,
          maxTime: 240,
          ttfs: '0:50',
          airTAT: '131:30',
          o2TAT: '43:30',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 130 },
          ],
          o2decoStops: [
            { depth: 20, time: 37 },
          ],
        },
        {
          minTime: 241,
          maxTime: 270,
          ttfs: '0:50',
          airTAT: '174:30',
          o2TAT: '51:30',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 173 },
          ],
          o2decoStops: [
            { depth: 20, time: 45 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '0:50',
          airTAT: '207:30',
          o2TAT: '57:30',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 206 },
          ],
          o2decoStops: [
            { depth: 20, time: 51 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '0:50',
          airTAT: '244:30',
          o2TAT: '67:30',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 243 },
          ],
          o2decoStops: [
            { depth: 20, time: 61 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '0:50',
          airTAT: '289:30',
          o2TAT: '69:30',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 288 },
          ],
          o2decoStops: [
            { depth: 20, time: 69 },
          ],
        },
        {
          minTime: 361,
          maxTime: 420,
          ttfs: '0:50',
          airTAT: '374:30',
          o2TAT: '95:30',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 373 },
          ],
          o2decoStops: [
            { depth: 20, time: 84 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          ttfs: '0:50',
          airTAT: '431:30',
          o2TAT: '117:30',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 431 },
          ],
          o2decoStops: [
            { depth: 20, time: 101 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          ttfs: '0:50',
          airTAT: '474:30',
          o2TAT: '133:30',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 473 },
          ],
          o2decoStops: [
            { depth: 20, time: 117 },
          ],
        },
      ]
    },
    {
      minfsw: 93,
      maxfsw: 95,
      rows: [
        {
          minTime: 126,
          maxTime: 130,
          ttfs: '1:00',
          airTAT: '3:40',
          o2TAT: '2:40',
          o2cp: 0.5,
          repetLetter: 'M',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 2 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 96,
          maxTime: 100,
          ttfs: '1:00',
          airTAT: '5:40',
          o2TAT: '3:40',
          o2cp: 0.5,
          repetLetter: 'N',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 4 },
          ],
          o2decoStops: [
            { depth: 20, time: 2 },
          ],
        },
        {
          minTime: 101,
          maxTime: 110,
          ttfs: '1:00',
          airTAT: '9:40',
          o2TAT: '5:40',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 8 },
          ],
          o2decoStops: [
            { depth: 20, time: 4 },
          ],
        },
        {
          minTime: 111,
          maxTime: 120,
          ttfs: '1:00',
          airTAT: '22:40',
          o2TAT: '8:40',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 21 },
          ],
          o2decoStops: [
            { depth: 20, time: 7 },
          ],
        },
        {
          minTime: 121,
          maxTime: 130,
          ttfs: '1:00',
          airTAT: '35:40',
          o2TAT: '13:40',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 34 },
          ],
          o2decoStops: [
            { depth: 20, time: 12 },
          ],
        },
        {
          minTime: 131,
          maxTime: 140,
          ttfs: '1:00',
          airTAT: '46:40',
          o2TAT: '17:40',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 45 },
          ],
          o2decoStops: [
            { depth: 20, time: 16 },
          ],
        },
        {
          minTime: 141,
          maxTime: 150,
          ttfs: '1:00',
          airTAT: '57:40',
          o2TAT: '20:40',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 56 },
          ],
          o2decoStops: [
            { depth: 20, time: 19 },
          ],
        },
        {
          minTime: 151,
          maxTime: 160,
          ttfs: '1:00',
          airTAT: '79:40',
          o2TAT: '24:40',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 78 },
          ],
          o2decoStops: [
            { depth: 20, time: 23 },
          ],
        },
        {
          minTime: 161,
          maxTime: 170,
          ttfs: '1:00',
          airTAT: '97:40',
          o2TAT: '27:40',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 96 },
          ],
          o2decoStops: [
            { depth: 20, time: 26 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '1:00',
          airTAT: '112:40',
          o2TAT: '31:40',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 111 },
          ],
          o2decoStops: [
            { depth: 20, time: 30 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '1:00',
          airTAT: '125:40',
          o2TAT: '36:40',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 125 },
          ],
          o2decoStops: [
            { depth: 20, time: 35 },
          ],
        },
        {
          minTime: 191,
          maxTime: 200,
          ttfs: '1:00',
          airTAT: '137:40',
          o2TAT: '45:40',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 136 },
          ],
          o2decoStops: [
            { depth: 20, time: 39 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '1:00',
          airTAT: '148:40',
          o2TAT: '49:40',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 147 },
          ],
          o2decoStops: [
            { depth: 20, time: 43 },
          ],
        },
        {
          minTime: 211,
          maxTime: 220,
          ttfs: '1:00',
          airTAT: '167:40',
          o2TAT: '53:40',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 166 },
          ],
          o2decoStops: [
            { depth: 20, time: 47 },
          ],
        },
        {
          minTime: 221,
          maxTime: 230,
          ttfs: '1:00',
          airTAT: '184:40',
          o2TAT: '56:40',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 183 },
          ],
          o2decoStops: [
            { depth: 20, time: 50 },
          ],
        },
        {
          minTime: 231,
          maxTime: 240,
          ttfs: '1:00',
          airTAT: '199:40',
          o2TAT: '59:40',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 198 },
          ],
          o2decoStops: [
            { depth: 20, time: 53 },
          ],
        },
        {
          minTime: 241,
          maxTime: 270,
          ttfs: '1:00',
          airTAT: '237:40',
          o2TAT: '68:40',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 236 },
          ],
          o2decoStops: [
            { depth: 20, time: 62 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '1:00',
          airTAT: '286:40',
          o2TAT: '85:40',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 285 },
          ],
          o2decoStops: [
            { depth: 20, time: 74 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '1:00',
          airTAT: '346:40',
          o2TAT: '94:40',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 345 },
          ],
          o2decoStops: [
            { depth: 20, time: 83 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '1:00',
          airTAT: '394:40',
          o2TAT: '103:40',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 393 },
          ],
          o2decoStops: [
            { depth: 20, time: 92 },
          ],
        },
        {
          minTime: 361,
          maxTime: 420,
          ttfs: '1:00',
          airTAT: '465:40',
          o2TAT: '129:40',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 464 },
          ],
          o2decoStops: [
            { depth: 20, time: 113 },
          ],
        },
      ]
    },
    {
      minfsw: 50,
      maxfsw: 55,
      rows: [
        {
          minTime: 75,
          maxTime: 75,
          ttfs: '1:10',
          airTAT: '2:50',
          o2TAT: '2:50',
          o2cp: 0.5,
          repetLetter: 'L',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 1 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 76,
          maxTime: 80,
          ttfs: '1:10',
          airTAT: '5:50',
          o2TAT: '3:50',
          o2cp: 0.5,
          repetLetter: 'M',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 4 },
          ],
          o2decoStops: [
            { depth: 20, time: 2 },
          ],
        },
        {
          minTime: 81,
          maxTime: 90,
          ttfs: '1:10',
          airTAT: '11:50',
          o2TAT: '6:50',
          o2cp: 0.5,
          repetLetter: 'N',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 10 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 91,
          maxTime: 100,
          ttfs: '1:10',
          airTAT: '18:50',
          o2TAT: '9:50',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 17 },
          ],
          o2decoStops: [
            { depth: 20, time: 8 },
          ],
        },
        {
          minTime: 101,
          maxTime: 110,
          ttfs: '1:10',
          airTAT: '35:50',
          o2TAT: '13:50',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 34 },
          ],
          o2decoStops: [
            { depth: 20, time: 12 },
          ],
        },
        {
          minTime: 111,
          maxTime: 120,
          ttfs: '1:10',
          airTAT: '49:50',
          o2TAT: '18:50',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 48 },
          ],
          o2decoStops: [
            { depth: 20, time: 17 },
          ],
        },
        {
          minTime: 121,
          maxTime: 130,
          ttfs: '1:10',
          airTAT: '60:50',
          o2TAT: '23:50',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 59 },
          ],
          o2decoStops: [
            { depth: 20, time: 22 },
          ],
        },
        {
          minTime: 131,
          maxTime: 140,
          ttfs: '1:10',
          airTAT: '85:50',
          o2TAT: '27:50',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 84 },
          ],
          o2decoStops: [
            { depth: 20, time: 26 },
          ],
        },
        {
          minTime: 141,
          maxTime: 150,
          ttfs: '1:10',
          airTAT: '106:50',
          o2TAT: '31:50',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 105 },
          ],
          o2decoStops: [
            { depth: 20, time: 30 },
          ],
        },
        {
          minTime: 151,
          maxTime: 160,
          ttfs: '1:10',
          airTAT: '124:50',
          o2TAT: '35:50',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 123 },
          ],
          o2decoStops: [
            { depth: 20, time: 34 },
          ],
        },
        {
          minTime: 161,
          maxTime: 170,
          ttfs: '1:10',
          airTAT: '139:50',
          o2TAT: '46:50',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 138 },
          ],
          o2decoStops: [
            { depth: 20, time: 40 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '1:10',
          airTAT: '152:50',
          o2TAT: '51:50',
          o2cp: 2,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 151 },
          ],
          o2decoStops: [
            { depth: 20, time: 45 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '1:10',
          airTAT: '170:50',
          o2TAT: '56:50',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 169 },
          ],
          o2decoStops: [
            { depth: 20, time: 50 },
          ],
        },
        {
          minTime: 191,
          maxTime: 200,
          ttfs: '1:10',
          airTAT: '191:50',
          o2TAT: '60:50',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 190 },
          ],
          o2decoStops: [
            { depth: 20, time: 54 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '1:10',
          airTAT: '209:50',
          o2TAT: '64:50',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 208 },
          ],
          o2decoStops: [
            { depth: 20, time: 58 },
          ],
        },
        {
          minTime: 211,
          maxTime: 220,
          ttfs: '1:10',
          airTAT: '225:50',
          o2TAT: '68:50',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 224 },
          ],
          o2decoStops: [
            { depth: 20, time: 62 },
          ],
        },
        {
          minTime: 221,
          maxTime: 230,
          ttfs: '1:10',
          airTAT: '240:50',
          o2TAT: '77:50',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 239 },
          ],
          o2decoStops: [
            { depth: 20, time: 66 },
          ],
        },
        {
          minTime: 231,
          maxTime: 240,
          ttfs: '1:10',
          airTAT: '255:50',
          o2TAT: '80:50',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 254 },
          ],
          o2decoStops: [
            { depth: 20, time: 69 },
          ],
        },
        {
          minTime: 241,
          maxTime: 270,
          ttfs: '1:10',
          airTAT: '314:50',
          o2TAT: '94:50',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 313 },
          ],
          o2decoStops: [
            { depth: 20, time: 83 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '1:10',
          airTAT: '381:50',
          o2TAT: '105:50',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 380 },
          ],
          o2decoStops: [
            { depth: 20, time: 94 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '1:10',
          airTAT: '433:50',
          o2TAT: '122:50',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 432 },
          ],
          o2decoStops: [
            { depth: 20, time: 106 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '1:10',
          airTAT: '475:50',
          o2TAT: '134:50',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 474 },
          ],
          o2decoStops: [
            { depth: 20, time: 118 },
          ],
        },
      ]
    },
    {
      minfsw: 56,
      maxfsw: 60,
      rows: [
        {
          minTime: 64,
          maxTime: 65,
          ttfs: '1:20',
          airTAT: '4:00',
          o2TAT: '3:00',
          o2cp: 0.5,
          repetLetter: 'L',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 2 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 66,
          maxTime: 70,
          ttfs: '1:20',
          airTAT: '9:00',
          o2TAT: '6:00',
          o2cp: 0.5,
          repetLetter: 'L',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 7 },
          ],
          o2decoStops: [
            { depth: 20, time: 4 },
          ],
        },
        {
          minTime: 71,
          maxTime: 80,
          ttfs: '1:20',
          airTAT: '16:00',
          o2TAT: '9:00',
          o2cp: 0.5,
          repetLetter: 'N',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 14 },
          ],
          o2decoStops: [
            { depth: 20, time: 7 },
          ],
        },
        {
          minTime: 81, 
          maxTime: 90,
          ttfs: '1:20',
          airTAT: '25:00',
          o2TAT: '12:00',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 23 },
          ],
          o2decoStops: [
            { depth: 20, time: 10 },
          ],
        },
        {
          minTime: 91,
          maxTime: 100,
          ttfs: '1:20',
          airTAT: '44:00',
          o2TAT: '17:00',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 42 },
          ],
          o2decoStops: [
            { depth: 20, time: 15 },
          ],
        },
        {
          minTime: 101,
          maxTime: 110,
          ttfs: '1:20',
          airTAT: '59:00',
          o2TAT: '23:00',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 57 },
          ],
          o2decoStops: [
            { depth: 20, time: 21 },
          ],
        },
        {
          minTime: 111,
          maxTime: 120,
          ttfs: '1:20',
          airTAT: '77:00',
          o2TAT: '28:00',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 75 },
          ],
          o2decoStops: [
            { depth: 20, time: 26 },
          ],
        },
        {
          minTime: 121,
          maxTime: 130,
          ttfs: '1:20',
          airTAT: '104:00',
          o2TAT: '33:00',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 102 },
          ],
          o2decoStops: [
            { depth: 20, time: 31 },
          ],
        },
        {
          minTime: 131,
          maxTime: 140,
          ttfs: '1:20',
          airTAT: '126:00',
          o2TAT: '37:00',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 124 },
          ],
          o2decoStops: [
            { depth: 20, time: 35 },
          ],
        },
        {
          minTime: 141,
          maxTime: 150,
          ttfs: '1:20',
          airTAT: '145:00',
          o2TAT: '48:00',
          o2cp: 2,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 143 },
          ],
          o2decoStops: [
            { depth: 20, time: 41 },
          ],
        },
        {
          minTime: 151,
          maxTime: 160,
          ttfs: '1:20',
          airTAT: '160:00',
          o2TAT: '55:00',
          o2cp: 2,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 158 },
          ],
          o2decoStops: [
            { depth: 20, time: 48 },
          ],
        },
        {
          minTime: 161,
          maxTime: 170,
          ttfs: '1:20',
          airTAT: '180:00',
          o2TAT: '60:00',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 178 },
          ],
          o2decoStops: [
            { depth: 20, time: 53 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '1:20',
          airTAT: '203:00',
          o2TAT: '66:00',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 201 },
          ],
          o2decoStops: [
            { depth: 20, time: 59 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '1:20',
          airTAT: '224:00',
          o2TAT: '71:00',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 222 },
          ],
          o2decoStops: [
            { depth: 20, time: 64 },
          ],
        },
        {
          minTime: 191,
          maxTime: 200,
          ttfs: '1:20',
          airTAT: '242:00',
          o2TAT: '80:00',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 240 },
          ],
          o2decoStops: [
            { depth: 20, time: 68 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '1:20',
          airTAT: '258:00',
          o2TAT: '85:00',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 256 },
          ],
          o2decoStops: [
            { depth: 20, time: 73 },
          ],
        },
        {
          minTime: 211,
          maxTime: 220,
          ttfs: '1:20',
          airTAT: '280:00',
          o2TAT: '89:00',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 278 },
          ],
          o2decoStops: [
            { depth: 20, time: 77 },
          ],
        },
        {
          minTime: 221,
          maxTime: 230,
          ttfs: '1:20',
          airTAT: '302:00',
          o2TAT: '94:00',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 300 },
          ],
          o2decoStops: [
            { depth: 20, time: 82 },
          ],
        },
        {
          minTime: 231,
          maxTime: 240,
          ttfs: '1:20', 
          airTAT: '323:00',
          o2TAT: '100:00',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 321 },
          ],
          o2decoStops: [
            { depth: 20, time: 88 },
          ],
        },
        {
          minTime: 241,
          maxTime: 270,
          ttfs: '1:20',
          airTAT: '400:00',
          o2TAT: '119:00',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 398 },
          ],
          o2decoStops: [
            { depth: 20, time: 102 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '1:20',
          airTAT: '458:00',
          o2TAT: '132:00',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 456 },
          ],
          o2decoStops: [
            { depth: 20, time: 115 },
          ],
        },
      ]
    },
    {
      minfsw: 61,
      maxfsw: 70,
      rows: [
        {
          minTime: 49,
          maxTime: 50,
          ttfs: '1:40',
          airTAT: '4:20',
          o2TAT: '3:20',
          o2cp: 0.5,
          repetLetter: 'K',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 2 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 51,
          maxTime: 55,
          ttfs: '1:40',
          airTAT: '11:20',
          o2TAT: '7:20',
          o2cp: 0.5,
          repetLetter: 'L',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 9 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 56,
          maxTime: 60,
          ttfs: '1:40',
          airTAT: '16:20',
          o2TAT: '10:20',
          o2cp: 0.5,
          repetLetter: 'M',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 14 },
          ],
          o2decoStops: [
            { depth: 20, time: 8 },
          ],
        },
        {
          minTime: 61,
          maxTime: 70,
          ttfs: '1:40',
          airTAT: '26:20',
          o2TAT: '15:20',
          o2cp: 0.5,
          repetLetter: 'N',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 24 },
          ],
          o2decoStops: [
            { depth: 20, time: 13 },
          ],
        },
        {
          minTime: 71,
          maxTime: 80,
          ttfs: '1:40',
          airTAT: '46:20',
          o2TAT: '19:20',
          o2cp: 1,
          repetLetter: 'O',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 44 },
          ],
          o2decoStops: [
            { depth: 20, time: 17 },
          ],
        },
        {
          minTime: 81,
          maxTime: 90,
          ttfs: '1:40',
          airTAT: '66:20',
          o2TAT: '26:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 64 },
          ],
          o2decoStops: [
            { depth: 20, time: 24 },
          ],
        },
        {
          minTime: 91,
          maxTime: 100,
          ttfs: '1:40',
          airTAT: '90:20',
          o2TAT: '33:20',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 88 },
          ],
          o2decoStops: [
            { depth: 20, time: 31 },
          ],
        },
        {
          minTime: 101,
          maxTime: 110,
          ttfs: '1:40',
          airTAT: '122:20',
          o2TAT: '45:20',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 120 },
          ],
          o2decoStops: [
            { depth: 20, time: 38 },
          ],
        },
        {
          minTime: 111,
          maxTime: 120,
          ttfs: '1:40',
          airTAT: '147:20',
          o2TAT: '51:20',
          o2cp: 2,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 145 },
          ],
          o2decoStops: [
            { depth: 20, time: 44 },
          ],
        },
        {
          minTime: 121,
          maxTime: 130,
          ttfs: '1:20',
          airTAT: '169:20',
          o2TAT: '58:20',
          o2cp: 2,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 167 },
          ],
          o2decoStops: [
            { depth: 20, time: 51 },
          ],
        },
        {
          minTime: 131,
          maxTime: 140,
          ttfs: '1:40',
          airTAT: '191:20',
          o2TAT: '66:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 189 },
          ],
          o2decoStops: [
            { depth: 20, time: 59 },
          ],
        },
        {
          minTime: 141,
          maxTime: 150,
          ttfs: '1:40',
          airTAT: '221:20',
          o2TAT: '78:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 219 },
          ],
          o2decoStops: [
            { depth: 20, time: 66 },
          ],
        },
        {
          minTime: 151,
          maxTime: 160,
          ttfs: '1:20',
          airTAT: '247:00',
          o2TAT: '85:00',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 244 },
            { depth: 30, time: 1 },
          ],
          o2decoStops: [
            { depth: 20, time: 72 },
            { depth: 30, time: 1 },
          ],
        },
        {
          minTime: 161,
          maxTime: 170,
          ttfs: '1:20',
          airTAT: '269:00',
          o2TAT: '91:00',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 265 },
            { depth: 30, time: 2 },
          ],
          o2decoStops: [
            { depth: 20, time: 78 },
            { depth: 30, time: 1 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '1:20',
          airTAT: '295:00',
          o2TAT: '97:00',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 289 },
            { depth: 30, time: 4 },
          ],
          o2decoStops: [
            { depth: 20, time: 83 },
            { depth: 30, time: 2 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '1:20',
          airTAT: '323:00',
          o2TAT: '103:00',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 316 },
            { depth: 30, time: 5 },
          ],
          o2decoStops: [
            { depth: 20, time: 88 },
            { depth: 30, time: 3 },
          ],
        },
        {
          minTime: 191,
          maxTime: 200,
          ttfs: '1:20',
          airTAT: '356:00',
          o2TAT: '115:00',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 345 },
            { depth: 30, time: 9 },
          ],
          o2decoStops: [
            { depth: 20, time: 93 },
            { depth: 30, time: 5 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '1:20',
          airTAT: '393:00',
          o2TAT: '122:00',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 378 },
            { depth: 30, time: 13 },
          ],
          o2decoStops: [
            { depth: 20, time: 98 },
            { depth: 30, time: 7 },
          ],
        },
        {
          minTime: 211,
          maxTime: 240,
          ttfs: '1:20',
          airTAT: '481:00',
          o2TAT: '140:00',
          o2cp: 5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 454 },
            { depth: 30, time: 25 },
          ],
          o2decoStops: [
            { depth: 20, time: 110 },
            { depth: 30, time: 13 },
          ],
        },
      ]
    },
    {
      minfsw: 71,
      maxfsw: 80,
      rows: [
        {
          minTime: 40,
          maxTime: 40,
          ttfs: '2:00',
          airTAT: '3:40',
          o2TAT: '3:40',
          o2cp: 0.5,
          repetLetter: 'J',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 1 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 41,
          maxTime: 45,
          ttfs: '2:00',
          airTAT: '12:40',
          o2TAT: '7:40',
          o2cp: 0.5,
          repetLetter: 'K',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 10 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 46,
          maxTime: 50,
          ttfs: '2:00',
          airTAT: '19:40',
          o2TAT: '11:40',
          o2cp: 0.5,
          repetLetter: 'M',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 17 },
          ],
          o2decoStops: [
            { depth: 20, time: 9 },
          ],
        },
        {
          minTime: 51,
          maxTime: 55,
          ttfs: '2:00',
          airTAT: '26:40',
          o2TAT: '15:40',
          o2cp: 0.5,
          repetLetter: 'M',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 24 },
          ],
          o2decoStops: [
            { depth: 20, time: 13 },
          ],
        },
        {
          minTime: 56,
          maxTime: 60,
          ttfs: '2:00',
          airTAT: '32:40',
          o2TAT: '18:40',
          o2cp: 1,
          repetLetter: 'N',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 30 },
          ],
          o2decoStops: [
            { depth: 20, time: 16 },
          ],
        },
        {
          minTime: 61,
          maxTime: 70,
          ttfs: '2:00',
          airTAT: '56:40',
          o2TAT: '24:40',
          o2cp: 1,
          repetLetter: 'O',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 54 },
          ],
          o2decoStops: [
            { depth: 20, time: 22 },
          ],
        },
        {
          minTime: 71,
          maxTime: 80,
          ttfs: '2:00',
          airTAT: '79:40',
          o2TAT: '32:40',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 77 },
          ],
          o2decoStops: [
            { depth: 20, time: 30 },
          ],
        },
        {
          minTime: 81,
          maxTime: 90,
          ttfs: '2:00',
          airTAT: '116:40',
          o2TAT: '46:40',
          o2cp: 1.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 114 },
          ],
          o2decoStops: [
            { depth: 20, time: 39 },
          ],
        },
        {
          minTime: 101,
          maxTime: 110,
          ttfs: '1:40',
          airTAT: '179:20',
          o2TAT: '61:20',
          o2cp: 2,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 171 },
            { depth: 30, time: 6 },
          ],
          o2decoStops: [
            { depth: 20, time: 51 },
            { depth: 30, time: 3 },
          ],
        },
        {
          minTime: 111,
          maxTime: 120,
          ttfs: '1:40',
          airTAT: '212:20',
          o2TAT: '71:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 200 },
            { depth: 30, time: 10 },
          ],
          o2decoStops: [
            { depth: 20, time: 59 },
            { depth: 30, time: 5 },
          ],
        },
        {
          minTime: 121,
          maxTime: 130,
          ttfs: '1:40',
          airTAT: '248:20',
          o2TAT: '86:20',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 232 },
            { depth: 30, time: 14 },
          ],
          o2decoStops: [
            { depth: 20, time: 67 },
            { depth: 30, time: 7 },
          ],
        },
        {
          minTime: 131,
          maxTime: 140,
          ttfs: '1:40',
          airTAT: '277:20',
          o2TAT: '94:20',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 258 },
            { depth: 30, time: 17 },
          ],
          o2decoStops: [
            { depth: 20, time: 73 },
            { depth: 30, time: 9 },
          ],
        },
        {
          minTime: 141,
          maxTime: 150,
          ttfs: '1:40',
          airTAT: '306:20',
          o2TAT: '102:20',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 285 },
            { depth: 30, time: 19 },
          ],
          o2decoStops: [
            { depth: 20, time: 80 },
            { depth: 30, time: 10 },
          ],
        },
        {
          minTime: 151,
          maxTime: 160,
          ttfs: '1:40',
          airTAT: '341:20',
          o2TAT: '114:20',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 318 },
            { depth: 30, time: 21 },
          ],
          o2decoStops: [
            { depth: 20, time: 86 },
            { depth: 30, time: 11 },
          ],
        },
        {
          minTime: 161,
          maxTime: 170,
          ttfs: '1:40',
          airTAT: '383:20',
          o2TAT: '121:20',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 354 },
            { depth: 30, time: 27 },
          ],
          o2decoStops: [
            { depth: 20, time: 90 },
            { depth: 30, time: 14 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '1:40',
          airTAT: '426:20',
          o2TAT: '130:20',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 391 },
            { depth: 30, time: 33 },
          ],
          o2decoStops: [
            { depth: 20, time: 96 },
            { depth: 30, time: 17 },
          ],
        },
        {
          minTime: 181,
          maxTime: 210,
          ttfs: '1:40',
          airTAT: '526:20',
          o2TAT: '158:20',
          o2cp: 5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 473 },
            { depth: 30, time: 51 },
          ],
          o2decoStops: [
            { depth: 20, time: 110 },
            { depth: 30, time: 26 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '1:20',
          airTAT: '393:00',
          o2TAT: '122:00',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 378 },
            { depth: 30, time: 13 },
          ],
          o2decoStops: [
            { depth: 20, time: 98 },
            { depth: 30, time: 7 },
          ],
        },
      ]
    },
    // page 503 90 fsw*****************************
    
  ]
};

export default usNavyAirDecompressionTable;
