import { ITableAirDeco } from '../types/interfaces';

const usNavyAirDecompressionTable: ITableAirDeco = {
  tableCode: 'USN-AIR-DECO',
  tableName: 'US Navy no decompression table revision 7 - Residual Nitrogen Time for No-Decompression Air Dives',
  tableData: [
    {
      minfsw: 0,
      maxfsw: 30,
      rows: [
        {
          minTime: 372,
          maxTime: 380,
          airTAT: '6:0',
          o2TAT: '2:0',
          ttfs: '0:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 5 },
          ],
          o2decoStops: [
            { depth: 20, time: 1 },
          ],
        },
        {
          minTime: 381,
          maxTime: 420,
          airTAT: '23:0',
          o2TAT: '6:0',
          ttfs: '0:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 22 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          airTAT: '43:0',
          o2TAT: '10:0',
          ttfs: '0:20',
          o2cp: 0.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 42 },
          ],
          o2decoStops: [
            { depth: 20, time: 9 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          airTAT: '72:0',
          o2TAT: '15:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 71 },
          ],
          o2decoStops: [
            { depth: 20, time: 14 },
          ],
        },
        {
          minTime: 541,
          maxTime: 600,
          airTAT: '93:0',
          o2TAT: '20:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 92 },
          ],
          o2decoStops: [
            { depth: 20, time: 19 },
          ],
        },
        {
          minTime: 601,
          maxTime: 660,
          airTAT: '121:0',
          o2TAT: '23:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 120 },
          ],
          o2decoStops: [
            { depth: 20, time: 22 },
          ],
        },
        {
          minTime: 661,
          maxTime: 720,
          airTAT: '159:0',
          o2TAT: '28:0',
          ttfs: '0:20',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 158 },
          ],
          o2decoStops: [
            { depth: 20, time: 27 },
          ],
        },
      ]
    },
    {
      minfsw: 31,
      maxfsw: 35,
      rows: [
        {
          minTime: 233,
          maxTime: 240,
          ttfs: '0:30',
          airTAT: '5:10',
          o2TAT: '3:10',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 4 },
          ],
          o2decoStops: [
            { depth: 20, time: 2 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '0:30',
          airTAT: '54:10',
          o2TAT: '14:10',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 53 },
          ],
          o2decoStops: [
            { depth: 20, time: 13 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '0:30',
          airTAT: '72:10',
          o2TAT: '19:10',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 71 },
          ],
          o2decoStops: [
            { depth: 20, time: 18 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '0:30',
          airTAT: '89:10',
          o2TAT: '23:10',
          o2cp: 1,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 88 },
          ],
          o2decoStops: [
            { depth: 20, time: 22 },
          ],
        },
        {
          minTime: 361,
          maxTime: 420,
          ttfs: '0:30',
          airTAT: '135:10',
          o2TAT: '30:10',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 134 },
          ],
          o2decoStops: [
            { depth: 20, time: 29 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          ttfs: '0:30',
          airTAT: '174:10',
          o2TAT: '44:10',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 173 },
          ],
          o2decoStops: [
            { depth: 20, time: 38 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          ttfs: '0:30',
          airTAT: '229:10',
          o2TAT: '51:10',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 228 },
          ],
          o2decoStops: [
            { depth: 20, time: 45 },
          ],
        },
        {
          minTime: 541,
          maxTime: 600,
          ttfs: '0:30',
          airTAT: '278:10',
          o2TAT: '59:10',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 277 },
          ],
          o2decoStops: [
            { depth: 20, time: 53 },
          ],
        },
        {
          minTime: 601,
          maxTime: 660,
          ttfs: '0:30',
          airTAT: '315:10',
          o2TAT: '69:10',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 314 },
          ],
          o2decoStops: [
            { depth: 20, time: 63 },
          ],
        },
        {
          minTime: 661,
          maxTime: 720,
          ttfs: '0:30',
          airTAT: '343:10',
          o2TAT: '82:10',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 342 },
          ],
          o2decoStops: [
            { depth: 20, time: 71 },
          ],
        },
      ]
    },
    {
      minfsw: 36,
      maxfsw: 40,
      rows: [
        {
          minTime: 164,
          maxTime: 170,
          ttfs: '0:40',
          airTAT: '7:20',
          o2TAT: '3:20',
          o2cp: 0.5,
          repetLetter: 'O',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 6 },
          ],
          o2decoStops: [
            { depth: 20, time: 2 },
          ],
        },
        {
          minTime: 171,
          maxTime: 180,
          ttfs: '0:40',
          airTAT: '15:20',
          o2TAT: '6:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: false,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 14 },
          ],
          o2decoStops: [
            { depth: 20, time: 5 },
          ],
        },
        {
          minTime: 181,
          maxTime: 190,
          ttfs: '0:40',
          airTAT: '22:20',
          o2TAT: '8:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 21 },
          ],
          o2decoStops: [
            { depth: 20, time: 7 },
          ],
        },
        {
          minTime: 191,
          maxTime: 200,
          ttfs: '0:40',
          airTAT: '28:20',
          o2TAT: '10:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 27 },
          ],
          o2decoStops: [
            { depth: 20, time: 9 },
          ],
        },
        {
          minTime: 201,
          maxTime: 210,
          ttfs: '0:40',
          airTAT: '40:20',
          o2TAT: '12:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 39 },
          ],
          o2decoStops: [
            { depth: 20, time: 11 },
          ],
        },
        {
          minTime: 211,
          maxTime: 220,
          ttfs: '0:40',
          airTAT: '53:20',
          o2TAT: '13:20',
          o2cp: 0.5,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 52 },
          ],
          o2decoStops: [
            { depth: 20, time: 12 },
          ],
        },
        {
          minTime: 221,
          maxTime: 230,
          ttfs: '0:40',
          airTAT: '65:20',
          o2TAT: '17:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 64 },
          ],
          o2decoStops: [
            { depth: 20, time: 16 },
          ],
        },
        {
          minTime: 231,
          maxTime: 240,
          ttfs: '0:40',
          airTAT: '76:20',
          o2TAT: '20:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: false,
          airDecoStops: [
            { depth: 20, time: 75 },
          ],
          o2decoStops: [
            { depth: 20, time: 19 },
          ],
        },
        {
          minTime: 241,
          maxTime: 270,
          ttfs: '0:40',
          airTAT: '102:20',
          o2TAT: '27:20',
          o2cp: 1,
          repetLetter: 'Z',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 101 },
          ],
          o2decoStops: [
            { depth: 20, time: 26 },
          ],
        },
        {
          minTime: 271,
          maxTime: 300,
          ttfs: '0:40',
          airTAT: '129:20',
          o2TAT: '34:20',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 128 },
          ],
          o2decoStops: [
            { depth: 20, time: 33 },
          ],
        },
        {
          minTime: 301,
          maxTime: 330,
          ttfs: '0:40',
          airTAT: '161:20',
          o2TAT: '44:20',
          o2cp: 1.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 160 },
          ],
          o2decoStops: [
            { depth: 20, time: 38 },
          ],
        },
        {
          minTime: 331,
          maxTime: 360,
          ttfs: '0:40',
          airTAT: '185:20',
          o2TAT: '50:20',
          o2cp: 2,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 184 },
          ],
          o2decoStops: [
            { depth: 20, time: 44 },
          ],
        },
        {
          minTime: 361,
          maxTime: 420,
          ttfs: '0:40',
          airTAT: '249:20',
          o2TAT: '62:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 248 },
          ],
          o2decoStops: [
            { depth: 20, time: 56 },
          ],
        },
        {
          minTime: 421,
          maxTime: 480,
          ttfs: '0:40',
          airTAT: '322:20',
          o2TAT: '79:20',
          o2cp: 2.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 321 },
          ],
          o2decoStops: [
            { depth: 20, time: 68 },
          ],
        },
        {
          minTime: 481,
          maxTime: 540,
          ttfs: '0:40',
          airTAT: '373:20',
          o2TAT: '91:20',
          o2cp: 3,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 372 },
          ],
          o2decoStops: [
            { depth: 20, time: 80 },
          ],
        },
        {
          minTime: 541,
          maxTime: 600,
          ttfs: '0:40',
          airTAT: '411:20',
          o2TAT: '104:20',
          o2cp: 3.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 410 },
          ],
          o2decoStops: [
            { depth: 20, time: 93 },
          ],
        },
        {
          minTime: 601,
          maxTime: 660,
          ttfs: '0:40',
          airTAT: '440:20',
          o2TAT: '119:20',
          o2cp: 4,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 439 },
          ],
          o2decoStops: [
            { depth: 20, time: 103 },
          ],
        },
        {
          minTime: 661,
          maxTime: 720,
          ttfs: '0:40',
          airTAT: '462:20',
          o2TAT: '128:20',
          o2cp: 4.5,
          repetLetter: 'N/A',
          surDo2Recom: true,
          surDo2Req: true,
          strictlySurDo2: true,
          exceptionalExposure: true,
          airDecoStops: [
            { depth: 20, time: 461 },
          ],
          o2decoStops: [
            { depth: 20, time: 112 },
          ],
        },
      ]
    },
    // page 497 45 fsw*****************************
    
  ]
};

export default usNavyAirDecompressionTable;
